### ISSUE TITLE
Java doesn't work either

### ISSUE THREAD

**Issue by gordonfreemanix** [DanielMartinus/Konfetti#121]
I did what was written in the document. I added it in build.gradle

implementation 'nl.dionsegijn:konfetti:1.1.3'
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.61"

The project, android studio freezes/crash. and the letter c in the class logo going. Please do for JAVA

Edit: I tried version 1.0.0

**Comment by DanielMartinus** [comment]
Hey Gordon,

Do you have any errors in logcat that you can share?

**Comment by gordonfreemanix** [comment]
Hi there! 
Sorry but I can't compile the application. 
For example when I add this line to my project; import nl.dionsegijn.konfetti.KonfettiView; 
Everything stops suddenly. Android studio freezes/crashes. The letter C in the class logo going. Screenshot: https://i.ibb.co/Pcp2JLb/ma.png

**Comment by DanielMartinus** [comment]
I setup a java project myself and added both implementations but I'm not able to reproduce it. Is it possible for you to share a demo project that reproduces the project so that I can have a look?

**Comment by gordonfreemanix** [comment]
I think it makes no sense to share the project. because I have the same problem even when I create a project from scratch.

![ss1](https://user-images.githubusercontent.com/51745645/73572759-a8674980-4482-11ea-8327-6e7ee26fa7c6.PNG)
![ss2](https://user-images.githubusercontent.com/51745645/73572761-a8ffe000-4482-11ea-9cb5-192fd01cd9a5.PNG)
![ss3](https://user-images.githubusercontent.com/51745645/73572763-a8ffe000-4482-11ea-9aa5-80c5d5918c10.PNG)
![ss4](https://user-images.githubusercontent.com/51745645/73572764-a8ffe000-4482-11ea-9b0e-37b9d7e56731.PNG)
![ss5](https://user-images.githubusercontent.com/51745645/73572765-a9987680-4482-11ea-841d-1ecefdb2873c.PNG)

**Comment by DanielMartinus** [comment]
Hi Gordon, 

It's not necessary to share **your** project but I ask you to share **a demo**, the one you just showed in the screenshots. If you can upload that to a public git repo for example I can have a look.

**Comment by gordonfreemanix** [comment]
Hi Daniel,
I already created an empty project. 
https://github.com/gordonfreemanix/Konfetti-Test

**Comment by gordonfreemanix** [comment]
Hello, 
Did you have time to review?

**Comment by DanielMartinus** [comment]
When I opened the project it indeed got errors. But when I fixed them the project runned as expected.

First I had to import the necessary classes:
```kotlin
import android.graphics.Color;
import nl.dionsegijn.konfetti.models.Shape;
import nl.dionsegijn.konfetti.models.Size;
```

And alsof change `viewKonfetti` to `konfettiView` on line 29:
```kotlin
.setPosition(-50f, konfettiView.getWidth() + 50f, -50f, -50f)
```

**Comment by gordonfreemanix** [comment]
Yes you are right when I added it worked very well. Awesome! 
But still the problem continues. I can't write anything else.
![ek1](https://user-images.githubusercontent.com/51745645/73607965-f2107b00-45cd-11ea-8453-09ded442cc50.PNG)

**Comment by DanielMartinus** [comment]
@gordonfreemanix Sorry I can't help you with the screenshot. There's an error somewhere in your MainActivity that doens't have to do anything with the Konfetti Library. Please follow the errors in your logs to solve it. As you can see with the last screenshot in this comment of yours (https://github.com/DanielMartinus/Konfetti/issues/121#issuecomment-580901953) the errors are sent in the build output. 

I'm closing this issue for now since it doesn't have anything to do with Konfetti itself.

**Comment by gordonfreemanix** [comment]
Hi @DanielMartinus 
What does it have to do with it? Your library it crashes the whole activity. Not a problem for me. I use another library but it's a big problem for you. I think this is a big problem and needs to be dealt with. This issues should not be closed! Thank you!

**Comment by janvalji** [comment]
@DanielMartinus  Hello, I have sent you an e-mail. I had to delete this account. I come across this issue in Google searches, can you delete it completely? Thank you
