### ISSUE TITLE
Can't use Shape in Android Studio using java

### ISSUE THREAD

**Issue by rohitjakhar** [DanielMartinus/Konfetti#146]
when i use Shape.Circle is show Expression expected

**Comment by dadou181295** [comment]
True, try Shape.RECT thought is deprecated!

**Comment by nelner** [comment]
Same also for use of Shape.DrawableShape with my own drawble

**Comment by Dilavar** [comment]
Use Shape like this.

Shape shape = new Shape.DrawableShape(getDrawable(R.drawable.ic_image), true);
        konfettiView.build()
                .addColors(Color.YELLOW, Color.GREEN, Color.MAGENTA)
                .setSpeed(1f, 5f)
                .setFadeOutEnabled(true)
                .setTimeToLive(2000L)
                .addShapes(shape, shape)
                .addSizes(new Size(12, 5f), new Size(16, 6f))
                .streamFor(30, 5000L);

**Comment by DanielMartinus** [comment]
@rohitjakhar see updated example in the readme [here](https://github.com/DanielMartinus/Konfetti#example-in-java)

Using a circle now also require you to call `INSTANCE` like this:
`Shape.Circle.INSTANCE`
