### ISSUE TITLE
Start Konfetti animations

### ISSUE THREAD

**Issue by alirehman** [DanielMartinus/Konfetti#15]
how to start animation after build in java cant see anything

**Comment by DanielMartinus** [comment]
Hi @alirehman 

Did you call one of the following methods after building the konfetti:

```Java
.burst(int amount);
.stream(Int particlesPerSecond);
.stream(Int particlesPerSecond, Long emittingTime);
.stream(Int particlesPerSecond, Int maxParticles);
.stream(Int particlesPerSecond, Long emittingTime, Int maxParticles);
```

If you did and it doesn't work show me a snippet of your code so I can see what you've tried

**Comment by Ravslee** [comment]
I have build it using example, but how to burst it please help!

**Comment by DanielMartinus** [comment]
Show some implementation code and I'll try to help you out

**Comment by Ravslee** [comment]
I have that code, which is shown in example. please show us code sample of burst thing!

**Comment by DanielMartinus** [comment]
Sure thing @Ravslee, I will post the most minimal possible working version this evening 👍

**Comment by DanielMartinus** [comment]
@Ravslee I've added a demo which implements Konfetti in a simple demo app here: https://github.com/DanielMartinus/Konfetti/pull/16

See the explanation of the Pull Request. In this demo I've used the same settings as you can find in the example of README.md in the root of this repository.

**Comment by DanielMartinus** [comment]
Closing this issue assuming all is fine now
