### ISSUE TITLE
Custom Shape in Java

### ISSUE THREAD

**Issue by hyang00** [DanielMartinus/Konfetti#168]
Hi, I was wondering if it was possible to add a custom shape using java instead of kotlin. If so, could you point me in the direction of the documentation for it? 

Best,
Hannah

**Comment by DanielMartinus** [comment]
Hi @hyang00,

I've updated the java example in the repo [here](https://github.com/DanielMartinus/Konfetti/blob/master/demo-simple-java/src/main/java/nl/dionsegijn/simple_demo/MainActivity.java#L22) to demonstrate how custom shapes work in Java.

Get your shape as a Drawable from the resources and then create a Drawable shape like this:
```Java
final Drawable drawable = ContextCompat.getDrawable(getApplicationContext(), R.drawable.ic_heart);
final Shape.DrawableShape drawableShape = new Shape.DrawableShape(drawable, true);
```

Then add your Drawable shape to the konfettti builder like this:

```Java
konfettiView.build()
        ...
        .addShapes(Shape.Square.INSTANCE, Shape.Circle.INSTANCE, drawableShape)
        ...
```

**Comment by hyang00** [comment]
Thank you!
