### ISSUE TITLE
width, x, y always 0

### ISSUE THREAD

**Issue by emilianocds** [DanielMartinus/Konfetti#169]
I added the view in my xml and alway I see the confetti at the same position, at the top left of the screen and does not look nice. 
I tried to debug and see the values, and width, x and y are always 0.
Im using ViewBinding and AndroidX.

**Comment by DanielMartinus** [comment]
Hey @emilianocds, it sounds like the views isn't properly layed out yet. So the Konfetti is starter too early. Can you post some code so that I can understand how and when you're starting Konfetti?
