### ISSUE TITLE
The compile dependency link is not working

### ISSUE THREAD

**Issue by gmathi** [DanielMartinus/Konfetti#17]
<img width="674" alt="screen shot 2017-07-30 at 10 15 27 am" src="https://user-images.githubusercontent.com/5333537/28754687-0b7a6c4a-7510-11e7-8c4b-4d9060ba702c.png">

**Comment by DanielMartinus** [comment]
It's working here, how did you put it in your gradle file?

**Comment by gmathi** [comment]
'compile 'nl.dionsegijn:konfetti:1.0.2' in my dependecies-> app.gradle
Then I guess there is a problem with my android studio. But I can't seem to find the problem as for some libraries it is not throwing the error. kinda weird!

**Comment by DanielMartinus** [comment]
Do you have the following the the project's `build.gradle` file?

```Groovy
allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by gmathi** [comment]
thanks for the help. Somehow changing the `compile` to `implementation` and doing a clean build worked. I am using gradle 3+
