### ISSUE TITLE
Control of gravity from the builder

### ISSUE THREAD

**Issue by carlfindahl** [DanielMartinus/Konfetti#184]
Hi, I would like to be able to control the magnitude and power of the gravity as it currently accelerates too quickly for our use case. I don't mind doing a PR for this if you accept them.

Currently, I have an initial speed of `0.01` to `1.0`, but by the time the Confetti is halfway down the screen it moves too fast.

**Comment by carlfindahl** [comment]
I found #158 that seems to do what I want, but after setting a dependency on `1.2.2` I can't find the function anywhere in the supplied files? :thinking:

**Comment by DanielMartinus** [comment]
Hey @carlfindahl, something should've gone wrong with the previous upload. I've just bumped the version to `1.2.3` and it now has `setMaxAcceleration` available.

**Comment by carlfindahl** [comment]
That should do it then, thanks!
