### ISSUE TITLE
Control of rotation from the builder

### ISSUE THREAD

**Issue by carlfindahl** [DanielMartinus/Konfetti#185]
I'd like control over the rotation speed of the confetti through the builder as they sometimes spin too fast for my current use case. Or rather, the designer thinks so but there are no controls for it at the moment :)

**Comment by carlfindahl** [comment]
PR Created #189

**Comment by DanielMartinus** [comment]
Good one! I'll review you PR. Being able to control the speed of the rotation indeed sounds like a nice thing to add

**Comment by carlfindahl** [comment]
Nice!

**Comment by DanielMartinus** [comment]
v1.2.4 has been released: https://github.com/DanielMartinus/Konfetti/releases/tag/v1.2.4

Thanks for your contribution!

**Comment by carlfindahl** [comment]
Thank you too!
