### ISSUE TITLE
Use drawable

### ISSUE THREAD

**Issue by amirarcane** [DanielMartinus/Konfetti#19]
I wonder if it is possible to use drawables as confetti. It would be great if we could pass pictures and drawables to the library.

**Comment by DanielMartinus** [comment]
Hi @amirarcane,

Thanks for creating an issue! For now I've not decided to include drawables. This library is focused on showing confetti. If you want to use drawables I would recommend other particle libraries that support this.

**Comment by amirarcane** [comment]
I wanted to use custom shapes rather than only circle and rectangle so I customized your library to use drawables as particles of confetti. Thanks for your great code.
