### ISSUE TITLE
enhancement:Please provide demo app source code

### ISSUE THREAD

**Issue by SergeyKodzha** [DanielMartinus/Konfetti#21]
It would be great if we have source code of the demo app.Because I observe completely different picture when I paste params from demo app into my code.
Also documentation would be much appreciated looks like setSpeed method behaves not the way I expect.

**Comment by DanielMartinus** [comment]
Hey @SergeyKodzha,

Totally agree I need to work on some better documentation. Give me some time to make that.

About providing code for the demo projects. In this repository there are two demo's:
A simple demo here: https://github.com/DanielMartinus/Konfetti/tree/master/demo-simple-java
And the demo you can download in the Play Store here: https://github.com/DanielMartinus/Konfetti/tree/master/demo-google-play

**Comment by DanielMartinus** [comment]
I will close this issue since I've provided you with the links to the demo projects. I'm planning to write better documentation on this project. For that I created this issue: https://github.com/DanielMartinus/Konfetti/issues/28
