### ISSUE TITLE
No direct method error, any idea?

### ISSUE THREAD

**Issue by keisa97** [DanielMartinus/Konfetti#217]
hello, 
when trying to implement the konfetti to my app(kotlin) i'm encountered error:

   java.lang.NoSuchMethodError: No direct method <init>(ILjava/lang/Object;Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V in class Lkotlin/jvm/internal/FunctionReferenceImpl; or its super classes (declaration of 'kotlin.jvm.internal.FunctionReferenceImpl' appears in /data/app/com.keisardevs.myapplication-jop33ftEpDAYvlt_i4oD6w==/base.apk!classes3.dex)

maybe got any idea what make this to happen?

**Comment by DanielMartinus** [comment]
Hey @keisa97, this is a possible duplicate of this issue. Please check: https://github.com/DanielMartinus/Konfetti/issues/193#issuecomment-691765015

Let me know if it helped

**Comment by keisa97** [comment]
@DanielMartinus  thanks that great!
changing Kotlin to 1.4.10 solved the problem!
