### ISSUE TITLE
Particles without recoloring

### ISSUE THREAD

**Issue by 0x7fs** [DanielMartinus/Konfetti#227]
Is there any way to have particles that are not recolored and just render normally? It seems that passing an empty array to addColors or skipping it results in all particles being rendered red.

**Comment by DanielMartinus** [comment]
@0x7fs assuming you're talking about using a `DrawableShape` you can set `tint` to false for that object

**Comment by 0x7fs** [comment]
@DanielMartinus Ahh yes that was it. Thanks for the help!
