### ISSUE TITLE
POSITION

### ISSUE THREAD

**Issue by Dave181295** [DanielMartinus/Konfetti#261]
please give us the correct position x,y,z,y for the center of the screen

**Comment by DanielMartinus** [comment]
@Dave181295 you have to calculate them yourself when the layout has drawn. Check for example https://stackoverflow.com/a/40714006

**Comment by Dave181295** [comment]
Can you please give me the axis points? I'm trying a lot of times to get it like the example you got in the doc
 ( center of layout from top to bottom)

thanks a lot

**Comment by DanielMartinus** [comment]
Sorry @Dave181295 this is highly dependent on the device that you're using and different for each device. Please follow the stackoverflow answer to retrieve the centered x,y coordinate of each screen.
