### ISSUE TITLE
Add a stop function to konfettiView

### ISSUE THREAD

**Issue by DanielMartinus** [DanielMartinus/Konfetti#27]
There is no way to stop active particle systems yet. This should be an easy implementation. 

- Add support to stop a single particle system
- Add support to stop alle particle systems alltogether
- Add emitter to create an indefinite stream which you can cancel with the stop support

**Comment by makinaman** [comment]
Could this be used in the meantime?
konfettiView.getSystems().clear();

**Comment by DanielMartinus** [comment]
yes, that will directly remove all the active particle systems. That'll mean that all drawing operations are directly interrupted though.

**Comment by sreekanth627** [comment]
DanielMartinus ,

Any work going on this right now? I also want to stop the particles after certain time. I want them to stay there with out moving indefinitely. is it possible with current existing methods. kindly share your thoughts.

**Comment by DanielMartinus** [comment]
@sreekanth627 if you want to have to particles to stream only for a certain amount of time you can use the [`.streamFor(particlesPerSecond: Int, maxParticles: Int)` ](https://github.com/DanielMartinus/Konfetti/blob/master/konfetti/src/main/java/nl/dionsegijn/konfetti/ParticleSystem.kt#L185) function

**Comment by DanielMartinus** [comment]
This has been added in the latest release [v1.1.3
](https://github.com/DanielMartinus/Konfetti/releases/tag/v1.1.3)

Stop a particle system by either calling:
- `konfettiView.stop(particleSystem)` with the particle instance as property which you get as reference when building a particle system with the KonfettiView.
- `particleSystem.stop()` 

Both will immediately stop the particles in the system from drawing and it'll clear them from the view.
