### ISSUE TITLE
Konfetti is behind the cardView?

### ISSUE THREAD

**Issue by passmanagerapp** [DanielMartinus/Konfetti#281]
Is this the behavior default that konfetti is always behind the cardView? See the attachment.

![Screenshot_1637402618](https://user-images.githubusercontent.com/78380553/142722373-35a5df5d-1e86-484a-b597-8ace44b94dbb.png)

**Comment by passmanagerapp** [comment]
ok, I solved the problem by adding android:translationZ="90dp" in XML.

**Comment by DanielMartinus** [comment]
@passmanagerapp hey, this not something related to Konfetti but something related to the Cardview. The elevation of the cardview and buttons is higher and thus drawing over KonfettiView

**Comment by passmanagerapp** [comment]
Yes, thanks Daniel we can close the issue
