### ISSUE TITLE
no access to nl.dionsegijn.konfetti.core methods

### ISSUE THREAD

**Issue by GhislainVerrier** [DanielMartinus/Konfetti#284]
Hello, 

with "implementation 'nl.dionsegijn:konfetti-xml:2.0.0'" I am able to import nl.dionsegijn.konfetti.xml.KonfettiView in java file but no  methods from nl.dionsegijn.konfetti.core.xxx

Am I doing something wrong? Or is there an extra implementation in Gradle for .core. functions?

Ghislain

**Comment by DanielMartinus** [comment]
@GhislainVerrier you're absolutely right. I made a mistake exposing core correctly from the xml library. I expect to have a release first thing tomorrow. Thanks for reporting the issue

**Comment by DanielMartinus** [comment]
@GhislainVerrier I just released version 2.0.1 and it now exposes the core classes. I was able to reproduce the issue with a clean sample project and the new version fixes it.
