### ISSUE TITLE
Upgrading to Konfetti 2.0.1 -> compilation warning

### ISSUE THREAD

**Issue by bmarty** [DanielMartinus/Konfetti#286]
See this PR: https://buildkite.com/matrix-dot-org/element-android/builds/5770

You can see the warning in the CI logs. I get this warning:

```sh
 w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/runner/.gradle/caches/transforms-3/41d05d97beee476cec3719b95e795601/transformed/jetified-kotlin-stdlib-jdk8-1.5.31.jar (version 1.5)
    /home/runner/.gradle/caches/transforms-3/cee23d725568e4b6759fa7d67a5ff9d9/transformed/jetified-kotlin-stdlib-jdk7-1.5.31.jar (version 1.5)
    /home/runner/.gradle/caches/transforms-3/0393eb3dd5596ff020754d2c6fc3662b/transformed/jetified-kotlin-stdlib-1.6.0.jar (version 1.6)
    /home/runner/.gradle/caches/transforms-3/78fef6caf680a33558f1ee83f52758dc/transformed/jetified-kotlin-stdlib-common-1.6.0.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
```

I am not sure how to get ride of this warning, if anyone has an idea.

**Comment by DanielMartinus** [comment]
Just to be sure. Are they 100% related to Konfetti? You don't see them if you don't upgrade Konfetti to 2.0.1?

**Comment by bmarty** [comment]
Yes. there is no warning like that with Konfetti 1.3.2.

The PR link is https://github.com/vector-im/element-android/pull/5079 by the way. In the description this is our CI build.

**Comment by DanielMartinus** [comment]
@bmarty I've just released a new version `2.0.2`. Would you be able to test whether the issue is still there for you?

**Comment by bmarty** [comment]
Thanks!
Trying right now in https://github.com/vector-im/element-android/pull/5079/commits/5f490b83ca31eba8b88015b2872152086f38e19a
Waiting for the CI to work a bit.

**Comment by DanielMartinus** [comment]
Hmm I see it's still the case and apparently to do so in combination with Jetified. I'll have to dive deeper into this to see if I can reproduce it

**Comment by bmarty** [comment]
I do not have the compilation warning anymore, probably due to the upgrade of one of our other dependency (Jitsi maybe).

I close the issue, thanks for the time you spent to check that.
