### ISSUE TITLE
Support to sdk lower than 23

### ISSUE THREAD

**Issue by the-thiago** [DanielMartinus/Konfetti#287]
Is it not possible to have a minimum sdk of 21? There is a significant amount of users below SDK 23.
Current min SDK for "nl.dionsegijn:konfetti-compose:2.0.1" is 23.

![versions](https://user-images.githubusercontent.com/39228080/153247216-72dde8e7-a4ae-407c-9e1f-77db23aa9726.png)

**Comment by the-thiago** [comment]
https://github.com/DanielMartinus/Konfetti/commit/080a7e9ee616915e654b4743ed7c4e77fad23a3a
The compose version was created already in api level 23, I think there is no problem updating it to API 21

**Comment by DanielMartinus** [comment]
Hey @the-thiago, I agree. I will look into it

**Comment by DanielMartinus** [comment]
Lowered the sdk version and will release it as soon as the other open PRs are tested and merged
