### ISSUE TITLE
Version 2.0 and 2.1 xml class not found

### ISSUE THREAD

**Issue by 0Flush0** [DanielMartinus/Konfetti#291]
i have added the implementation to my build.gradle, but in xml the KonfettiView is not found:
These are my dependencies:
dependencies {

    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'nl.dionsegijn:konfetti-xml:2.0.1'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}

**Comment by DanielMartinus** [comment]
@0Flush0 hey flush, the import looks good. What View did you try to import. Did you use the correct path that includes `xml` like this?

```xml
<nl.dionsegijn.konfetti.xml.KonfettiView
    android:id="@+id/konfettiView"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
```

**Comment by cklim228** [comment]
> i have added the implementation to my build.gradle, but in xml the KonfettiView is not found: These are my dependencies: dependencies {
> 
> ```
> implementation 'androidx.appcompat:appcompat:1.4.1'
> implementation 'com.google.android.material:material:1.5.0'
> implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
> implementation 'androidx.legacy:legacy-support-v4:1.0.0'
> implementation 'nl.dionsegijn:konfetti-xml:2.0.1'
> testImplementation 'junit:junit:4.+'
> androidTestImplementation 'androidx.test.ext:junit:1.1.3'
> androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
> ```
> 
> }

e0a484f75f4dd0956ca2036d1d417e837b907f10

**Comment by 0Flush0** [comment]
@DanielMartinus  Thank you for your quick reply, im am using the correct path i think.
This is the error:
Class referenced in the layout file, "nl.dionsegijn.konfetti.xml.KonfettiVew", was not found in the project or the libraries. Cannot resolve class nl.dionsegijn.konfetti.xml.KonfettiVIew

![Screenshot 2022-02-12 130644](https://user-images.githubusercontent.com/93215916/153710648-0ff7c50b-6b77-49da-9e58-caf6f02ed4b4.png)

(Sry for bad english)

**Comment by DanielMartinus** [comment]
Strange, would you be able to provide a sample project? I have no issues here. Tried old and new projects and all are able to import the KonfettiView

**Comment by 0Flush0** [comment]
@DanielMartinus Thanks again for the reply, i have created a test repository if you want to look into my issue.
Maybe its just me being incompetent and i hope i dont have wasted your time 
https://github.com/0Flush0/test
Sry for bad engish again :)

**Comment by DanielMartinus** [comment]
No worries. 

I opened the project and don't encounter any issues.

Looking at the list of external libraries everything seems to be fine.

<img width="518" alt="CleanShot 2022-02-25 at 18 14 23@2x" src="https://user-images.githubusercontent.com/1636897/155758158-96b46fb1-03f5-4ef1-8ec8-f6e9225c1571.png">

Do you see any gradle build errors in Android Studio maybe?

**Comment by 0Flush0** [comment]
When running a clean build i get some issues, the report might help, but i am not seeing threw this:

[lint-results.zip](https://github.com/DanielMartinus/Konfetti/files/8143079/lint-results.zip)
:

**Comment by DanielMartinus** [comment]
Lint won't show any issues related to this. Does your gradle console output any issue?

**Comment by 0Flush0** [comment]
I have found a promising issue, that could relate to this problem. There is a note, that some input files use or override a deprecated API:
> Task :app:mergeReleaseAssets
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by DanielMartinus** [comment]
I don't think that is the issue. If you run `./gradlew build` in the terminal of the folder of your project can you share the error that's shown?

**Comment by saldous** [comment]
I'm getting this same issue. I import the library successfully in build.gradle, but when I try and add this to the xml it can't find it.

```
<nl.dionsegijn.konfetti.xml.KonfettiView
    android:id="@+id/konfettiView"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
```
<img width="511" alt="image" src="https://user-images.githubusercontent.com/3334306/229509376-369d66f4-8986-4113-8c31-5b16a89dd1a1.png">


Were you able to solve the issue?

**Comment by 0Flush0** [comment]
I am sorry, but i could'nt solve the issue at the time and it was just not worth the hassle for me, to continue searching for a solution. Hope you find one :)
