### ISSUE TITLE
Slow down the party show

### ISSUE THREAD

**Issue by ShkurtiA** [DanielMartinus/Konfetti#310]
I tried playing with speed and dumping but I cant manage to slow down the party.
I see that you use some variables like gravity and force, is it possible to access them or some other way to achieve slowed down party

smth with the speed of this lottie https://lottiefiles.com/74680-confetti

**Comment by DanielMartinus** [comment]
@ShkurtiA have you already played with [`Size`](https://github.com/DanielMartinus/Konfetti/blob/main/konfetti/core/src/main/java/nl/dionsegijn/konfetti/core/models/Size.kt)?  

If you create your custom Size class and play around with mass you could potentially slow down the fall. It will affect the shooting and other things as well. It's been a while for me so I would have to play around and look in the code to find out what you exactly need to achieve this.
