### ISSUE TITLE
Feature request: Haptic feedback

### ISSUE THREAD

**Issue by kit0kat** [DanielMartinus/Konfetti#318]
It would be great if you could set a short vibration (e.g. VibrationEffect.EFFECT_TICK) to be triggered every time a confetti particle is emitted.

**Comment by DanielMartinus** [comment]
@kit0kat thanks for the suggestion. What I recommend doing here is, if you don't have too much randomisation. You can simulate the Effect kick yourself when starting the particle system.

**Comment by DanielMartinus** [comment]
Close this one as I'm not planning to implement this
