### ISSUE TITLE
Update LICENSE file content

### ISSUE THREAD

**Issue by mykolapuliaiev** [DanielMartinus/Konfetti#326]
Hello. In README there is a statement `Konfetti is released under the ISC license`. And in Maven I can see that artifact is marked with ISC license. I understand that ISC is a simplified MIT license. However in LICENSE file there is a text for MIT License. Is it possible to update text of LICENSE file with text of ISC license?

**Comment by DanielMartinus** [comment]
Fixed, thank you!
