### ISSUE TITLE
Documentation for what direction means

### ISSUE THREAD

**Issue by PaulWoitaschek** [DanielMartinus/Konfetti#33]
It would be great if you could add for the direction, what exactly it means.

Is it radian? Is it degrees? Let that be reflected in the parameter names. `minDirectionDegrees`.
Describe what 0 degrees mean. Is it top? Is it bottom? Is it right?

**Comment by DanielMartinus** [comment]
Yes documentation is still high on my list. I'll have to find some time for that. Thanks for creating the Issue
