### ISSUE TITLE
Size : Rounding errors and property naming

### ISSUE THREAD

**Issue by PaulWoitaschek** [DanielMartinus/Konfetti#34]
For size the property `size` should be called `sizeInDp`. 

`val Size.sizeDp: Int` should be named `sizeInPx` as it's actually the pixels. It should not be casted `toInt()` as it's inaccurate. As it's only used in `Confetti` as ` private var width = size.sizeDp.toFloat()` it should just be left as a float.

Also `mass` tells me quite nothing about what it does. What does negative mass mean? What does positive mass mean? 
What does mass 0 mean? (it actually crashes the app as in `Vector` you are dividing by that value). So better validate the argument:

```kotlin
  data class Size(val sizeInDp: Int, val mass: Float = 5f) {

    internal val sizeInPx: Float
      get() = sizeInDp * Resources.getSystem().displayMetrics.density

    init {
      require(mass != 0F) { "mass=$mass must be != 0" }
    }
  }
```

**Comment by DanielMartinus** [comment]
Thanks for the feedback @PaulWoitaschek 

I've created a pull request, if you have some time to review I would be very happy with that.
