### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RemmyChen** [DanielMartinus/Konfetti#35]
Hi, this isn't an issue, I thought you made a really cool thing that I'd like to include in my app that at some point I'll be deploying to Google Play Store, but I didn't really understand what the license part meant and just wanted to seek out clarification - is it ok if I include your api? How do I cite and acknowledge your work? Please let me know, thanks!

**Comment by DanielMartinus** [comment]
Sure it's ok to include it in your app. The license is just a simplified version of the MIT license and is mostly covering myself not to be held responsible on the way how other people are using my work. You're free to use or fork my work as the license describes!

**Comment by RemmyChen** [comment]
Great, thanks for letting me know! I'm building my first app and am pretty excited to add some confetti to it!

**Comment by RemmyChen** [comment]
sorry follow up question, do you know how I can set the background of konfettiview to transparent? i tried multiple ways and haven't found a working one. please let me know, thanks!

**Comment by DanielMartinus** [comment]
Are you sure the background isn't set on the view? It should be transparent already. If not can you open a new issue and post the XML of your layout? That way, if anyone else have this problem they can find it back in the issue list.
