### ISSUE TITLE
Disable konfetti for instrumentation tests

### ISSUE THREAD

**Issue by premnirmal** [DanielMartinus/Konfetti#39]
Is there a way to do this accommodate this in to the library without explicitly disabling konfetti in instrumentation tests?

**Comment by DanielMartinus** [comment]
Sorry I have no idea what you actually mean

**Comment by premnirmal** [comment]
When running instrumentation tests on Android, animations should be disabled. If you disable animations on your device via developer settings, app animations should be disabled.

The konfetti animation still runs when animations are disabled, and it also runs in instrumentation tests. This suggests that the library isn't adhering to Android guidelines. For example: the android progress bar does not spin when running instrumentation tests-this is correct implementation.

An application developer should not have to write code that manually disables the konfetti animation, the library should do that automatically.

Does that make sense?

**Comment by DanielMartinus** [comment]
Ok, that makes sense. The Konfetti app currently implements a game-loop mechanism for updating the canvas. This is indeed running independent from the Animations of Android hence you're not able to turn them off, control the animation speed or by default disabled in instrumental tests.

I'll have to find out if support is available in the api of the platform to detect if the instrumental tests are running. If you have any pointers, any help is welcome.
