### ISSUE TITLE
Change axis acceleration option

### ISSUE THREAD

**Issue by GBL147852** [DanielMartinus/Konfetti#48]
I wonder if it is possible to change axis acceleration, to make the confettis fall faster/slower, or even fall in a constant velocity. I think it would be great to manipulate the acceleration, specially on y axis.

Oh, and thanks for the great lib!

**Comment by DanielMartinus** [comment]
Hey @GBL147852, yeah I haven't exposed that api part of the library. It should be possible to easily manipulate that if I open that part up. I'll see what I can do about it

**Comment by DanielMartinus** [comment]
@GBL147852 I know it has been two years so I understand situation has changed and it isn't necessary anymore, though I made some changes and was wondering if it aligns with your suggestion.

I've implemented a way to disable and set a maxAcceleration value to control the behavior and endless acceleration of the particles. Is the example in the GIF what you meant?

![ezgif-6-49f359998786](https://user-images.githubusercontent.com/1636897/86518934-c4a65280-be35-11ea-9393-bf9a88c7bd3f.gif)

**Comment by GBL147852** [comment]
Yeah! That's just how I meant. Great job! \o

**Comment by DanielMartinus** [comment]
I didn't expect a response so soon 😄 Thanks, then I'll do some more testing and publish it in the next release 👍

**Comment by DanielMartinus** [comment]
This is now available in the latest release (v1.2.2)
