### ISSUE TITLE
Typos in docs

### ISSUE THREAD

**Issue by Gibolt** [DanielMartinus/Konfetti#56]
`new Size(12, 5)` instead of `Size(12)`
`viewKonfetti.getWidth()` instead of `viewKonfetti.width`

Add dependency `implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.41'`

**Comment by DanielMartinus** [comment]
The example is written for Kotlin, I'll make that more clear in the documentation and/or add a Java example. I'll also add the latter to the readme.
