### ISSUE TITLE
How do we know when the konfetti animation is over?

### ISSUE THREAD

**Issue by parthanjaria** [DanielMartinus/Konfetti#61]
I have used this in my project, and would like to know that where does the callback go when the konfetti is over?

**Comment by DanielMartinus** [comment]
Hi @parthanjaria,

You're right, I was under the assumption that `onParticleSystemUpdateListener` was a public callback but I see it's set to private. This might have been a coincidence when removing some warnings. 

I'll make this callback public again in the next release

**Comment by rpattabi** [comment]
I see 1.1.2 is yet to have this. Without this callback, is there a way to check if the confetti is running or completed similar to `dialog.isShowing()`, `fragment.isVisible()`, etc?

**Comment by DanielMartinus** [comment]
In the meantime by calling `getActiveSystems` on KonfettiView. If it's returning one or more systems it means it's active. Systems are being automatically removed once they are done rendering.

**Comment by DanielMartinus** [comment]
The listener is now publicly available. It'll look like this in Kotlin:

```Kotlin
viewKonfetti.onParticleSystemUpdateListener = object : OnParticleSystemUpdateListener {
    override fun onParticleSystemStarted(view: KonfettiView, system: ParticleSystem, activeSystems: Int) {
        
    }

    override fun onParticleSystemEnded(view: KonfettiView, system: ParticleSystem, activeSystems: Int) {
        
    }
}
```
