### ISSUE TITLE
How to stop some desired konfetti particles?

### ISSUE THREAD

**Issue by Rajeshwari1997** [DanielMartinus/Konfetti#63]
I have used this library in my project and I would like to know how should I make some of the konfetti particles to stop permanently on the display

**Comment by DanielMartinus** [comment]
@Rajeshwari1997 could you try and describe in more details what you mean with **some of the particles** to **stop permanently** on the display?

**Comment by DanielMartinus** [comment]
@Rajeshwari1997 I'm closing this issue, please re-open the issue if you have more details for me.
