### ISSUE TITLE
How to show konfetti with dialog?

### ISSUE THREAD

**Issue by parthanjaria** [DanielMartinus/Konfetti#64]
I would like to show this konfetti animation when a dialog pop's up. Now if i make the dialog full screen and add the konfetti to it, then when i add animation to the dialog , when the dialog is appearing the konfetti animation dsn't look good.

Is there any way possible?

**Comment by DanielMartinus** [comment]
What do you mean with "doesn't look good"?

**Comment by OneManStudioDotSe** [comment]
I have a similar problem. While being inside a fragment, I show a dialog and after it is visible, I start the confetti. What happens is that the confetti shows up behind the dialog and also behind the darkened background that is created by default from the dialogs.

@DanielMartinus can you help us with an example of how to show confetti while having a dialog open? Should we have a custom dialog or is it a matter of placing the confetti view at the correct place?

What is a common scenario I think is to let the user do whatever they want to do, show a dialog that confirms their action and then start the confetti on top of everything, therefore sprinkling color all over :)

Any suggestions/examples/ideas about how we can accomplish i?

**Comment by DanielMartinus** [comment]
@OneManStudioDotSe thanks for the explanation.

There's actually a way to solve that but I hope there are other ways to achieve this without opening an extra activity over the dialog. So one way I know and that is by using a transparant activity as overlay that renders the confetti. 

### Create an activity
If you create, for example, a `ConfettiOverlayActivity` you can set its window flag to `FLAG_NOT_TOUCHABLE` in the onCreate. This will make sure that when the activity is opened as overlay you can still dismiss or tap on the dialog.
As layout of this activity you can just set the KonfettiView as root layout and have the activity contain the code to start the confetti when it's opened in the `onCreate`

### Open and close the activity
Now all you need to do is open this activity when you show the dialog and you need to close the activity when you close the dialog. You can listen to dismiss events of the dialog itself for that.

### Make the activity translucant
When creating the activity in your manifest it's important that it has a style containing the following attribute:
`<item name="android:windowTranslucentStatus">true</item>`

Let me know if it workedm if you found a better solution or if you need any help!

**Comment by parthanjaria** [comment]
This works. Thanks.

**Comment by Menuoff** [comment]
> @OneManStudioDotSe thanks for the clear explanation.
> 
> There's actually a way to solve that but I hope there are other ways to achieve this without opening an extra activity over the dialog. So one way I know and that is by using a transparant activity as overlay that renders the confetti.
> 
> ### Create an activity
> If you create, for example, a `ConfettiOverlayActivity` you can set its window flag to `FLAG_NOT_TOUCHABLE` in the onCreate. This will make sure that when the activity is opened as overlay you can still dismiss or tap on the dialog. As layout of this activity you can just set the KonfettiView as root layout and have the activity contain the code to start the confetti when it's opened in the `onCreate`
> 
> ### Open and close the activity
> Now all you need to do is open this activity when you show the dialog and you need to close the activity when you close the dialog. You can listen to dismiss events of the dialog itself for that.
> 
> ### Make the activity translucant
> When creating the activity in your manifest it's important that it has a style containing the following attribute so that it becomes transparant. `<item name="android:windowTranslucentStatus">true</item>`
> 
> Let me know if it worked, if you found a better solution or if you need any help!

Thanx for your attention . In my opinion better way with more performance to achieve this goal is creating new transparent dialog with same style as you wrote and set to its style. these days single activity architecture is popular. I tried to create a new activity . but I got black background as activity background with animation in/out effect . I don't know why. but by using another transparent dialog with match parent width height solved my need.

**Comment by NimaaZx** [comment]
> @OneManStudioDotSe thanks for the clear explanation.
> 
> There's actually a way to solve that but I hope there are other ways to achieve this without opening an extra activity over the dialog. So one way I know and that is by using a transparant activity as overlay that renders the confetti.
> 
> ### Create an activity
> If you create, for example, a `ConfettiOverlayActivity` you can set its window flag to `FLAG_NOT_TOUCHABLE` in the onCreate. This will make sure that when the activity is opened as overlay you can still dismiss or tap on the dialog. As layout of this activity you can just set the KonfettiView as root layout and have the activity contain the code to start the confetti when it's opened in the `onCreate`
> 
> ### Open and close the activity
> Now all you need to do is open this activity when you show the dialog and you need to close the activity when you close the dialog. You can listen to dismiss events of the dialog itself for that.
> 
> ### Make the activity translucant
> When creating the activity in your manifest it's important that it has a style containing the following attribute so that it becomes transparant. `<item name="android:windowTranslucentStatus">true</item>`
> 
> Let me know if it worked, if you found a better solution or if you need any help!

Thanx for your attention . In my opinion better way with more performance to achieve this goal is creating new transparent dialog with same style as you wrote and set to its style. these days single activity architecture is popular. I tried to create a new activity . but I got black background as activity background with animation in/out effect . I don't know why. but by using another transparent dialog with match parent width/height solved my need
