### ISSUE TITLE
Konfetti doesn't work onAnimationEnd

### ISSUE THREAD

**Issue by dariorios** [DanielMartinus/Konfetti#66]
KonfettiView doesn't work onAnimationEnd in an class that  implements Animation.AnimationListener. Still, it doesn't give any kind of error.

` public void onAnimationEnd(Animation animation) {
        Toast toast = Toast.makeText("test");
        toast.show();

        konfettiView.build()
                .addColors(Color.YELLOW, Color.GREEN, Color.MAGENTA)
                .setDirection(0.0, 359.0)
                .setSpeed(1f, 5f)
                .setFadeOutEnabled(true)
                .setTimeToLive(2000L)
                .addShapes(Shape.RECT, Shape.CIRCLE)
                .addSizes(new Size(12, 5f))
                .setPosition(-50f, konfettiView.getWidth() + 50f, -50f, -50f)
                .streamFor(300, 5000L);

    }`

Any ideas?

**Comment by DanielMartinus** [comment]
I don't see anything that's wrong here. Are you sure the KonfettiView is visible/big enough on the screen?
