### ISSUE TITLE
Infinite Particles

### ISSUE THREAD

**Issue by erikgallegos** [DanielMartinus/Konfetti#69]
It would be useful to have an option to infinitely emit particles.

Something like this:
`KonfettiView.build().streamFor(xxx, INFINITE)`

**Comment by DanielMartinus** [comment]
I see what I can do 👍

**Comment by Kevinrob** [comment]
@erikgallegos @DanielMartinus #76 ✌

**Comment by DanielMartinus** [comment]
Thanks for contributing @Kevinrob. To implement support for infinite particles I was thinking to build support for all emitters instead of 1 as @erikgallegos suggests with the `INFINITE` param.

Though your emitter can be used already, more about it here: https://github.com/DanielMartinus/Konfetti/pull/26

**Comment by DanielMartinus** [comment]
I just created a commit to stream particles for an indefinite amount of time here: https://github.com/DanielMartinus/Konfetti/commit/ae8ca958a51a7c0cd889955c373bc524245ccd21

The way it works is almost similar as @erikgallegos proposes. Set `INDEFINITE` als `emittingTime` when using **streamFor**.

```Kotlin
viewKonfetti.build()
    ...
    .streamFor(300, INDEFINITE)
```

You can only stop the particle stream manually by either calling:
`konfettiView.reset()` or `konfettiView `stopGracefully()`

Both functions are also newly added. The first stops imediatelly with rendering, the latter stops creating new konfetti particles and the ones already drawn will live out their lifetime until everything is done.

This change hasn't been released yet, I'll continue to do some testing this weekend and then start preparing the release.

**Comment by DanielMartinus** [comment]
This feature is added in `v1.2.1` more info about the release [here](https://github.com/DanielMartinus/Konfetti/releases/tag/v1.2.1)

Information on its usage can also be found in the readme [here](https://github.com/DanielMartinus/Konfetti#indefinite-streams)
