### ISSUE TITLE
Particles alignment problem

### ISSUE THREAD

**Issue by durgesh2014** [DanielMartinus/Konfetti#70]
When I call below code directly in onCreate method of my activity, I get particles coming down from left of the screen. But, If I put the same code in onClick event, I see that particles come down from the center.

```Kotlin
oncreate() {
  konfettiView.build()
        .addColors(Color.rgb(255, 36, 0), Color.rgb(120, 116, 242), Color.rgb(255, 232, 103))
        //.addColors(Color.rgb(168,100,253), Color.rgb(255,113,141), Color.rgb(120,255,68))
        .setDirection(0.0, 359.0)
        .setSpeed(1f, 5f)
        .setFadeOutEnabled(true)
        .setTimeToLive(2000L)
        .addShapes(Shape.RECT, Shape.CIRCLE)
        .addSizes(new Size(12, 5f))
        .setPosition(-50f, konfettiView.getWidth() + 50f, -50f, -50f)
        .streamFor(300, 5000L);
}

konfettiView.setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(final View view) {
          konfettiView.build()
            .addColors(Color.rgb(255, 36, 0), Color.rgb(120, 116, 242), Color.rgb(255, 232, 103))
            //.addColors(Color.rgb(168,100,253), Color.rgb(255,113,141), Color.rgb(120,255,68))
            .setDirection(0.0, 359.0)
            .setSpeed(1f, 5f)
            .setFadeOutEnabled(true)
            .setTimeToLive(2000L)
            .addShapes(Shape.RECT, Shape.CIRCLE)
            .addSizes(new Size(12, 5f))
            .setPosition(-50f, konfettiView.getWidth() + 50f, -50f, -50f)
            .streamFor(300, 5000L);
      }
});
```

**Comment by samwoodall** [comment]
If you specify maxX with a float only, not using konfettiView.getWidth() you still should be able to position the konfetti where you want. The konfettiView width is 0 in onCreate

**Comment by durgesh2014** [comment]
Thank you for your reply. I figured it out by getting screen width.
By the way yesterday only I published my app on play store.

Please check out the link given below.

https://play.google.com/store/apps/details?id=com.crackitinterview.cinterviewqa

**Comment by dionassydqi** [comment]
I also experienced the same problem, can you write down your code?

**Comment by durgesh2014** [comment]
final KonfettiView konfettiView = findViewById(R.id.viewKonfetti);
DisplayMetrics display = new DisplayMetrics();
getWindowManager().getDefaultDisplay().getMetrics(display);
konfettiView.build()
        .addColors(Color.rgb(255, 36, 0), Color.rgb(120, 116, 242),
Color.rgb(255, 232, 103))
        //.addColors(Color.rgb(168,100,253), Color.rgb(255,113,141),
Color.rgb(120,255,68))
        .setDirection(0.0, 359.0)
        .setSpeed(1f, 5f)
        .setFadeOutEnabled(true)
        .setTimeToLive(2000L)
        .addShapes(Shape.RECT, Shape.CIRCLE)
        .addSizes(new Size(12, 5f))
        .setPosition(-50f, display.widthPixels + 50f, -50f, -50f)
        .streamFor(300, 5000L);

**Comment by dionassydqi** [comment]
Thank you for your answer, this is very helpful. Success for you

**Comment by durgesh2014** [comment]
Thank you for your wishes 😊😊

**Comment by DanielMartinus** [comment]
Great that it's been solved, I'm closing this issue
