### ISSUE TITLE
getWidth Konfetti

### ISSUE THREAD

**Issue by dionassydqi** [DanielMartinus/Konfetti#71]
I am making a simple game application, I want when the player finishes the game confetti will appear, I have applied it but the width of the confetti does not fill the screen. How do I get the width of the screen that matches the match for confetti?

```Kotlin
konfettiView.build ()
                .addColors (Color.YELLOW, Color.GREEN, Color.MAGENTA, Color.RED, Color.GREEN)
                .setDirection (0.0, 359.0)
                .setSpeed ​​(1f, 5f)
                .setFadeOutEnabled (true)
                .setTimeToLive (3000L)
                .addShapes (Shape.RECT, Shape.CIRCLE)
                .addSizes (Size (10), Size (12, 6f))
                .setPosition (-50f, konfettiView.width + 50f, -50f, -50f)
                .streamFor (300, 5000L)
```

**Comment by samwoodall** [comment]
You can do this if you want to use the konfettiView width
```
viewKonfetti.viewTreeObserver.addOnGlobalLayoutListener {
            viewKonfetti.build()
                .addColors (Color.YELLOW, Color.GREEN, Color.MAGENTA, Color.RED, Color.GREEN)
                .setDirection (0.0, 359.0)
                .setSpeed ​​(1f, 5f)
                .setFadeOutEnabled (true)
                .setTimeToLive (3000L)
                .addShapes (Shape.RECT, Shape.CIRCLE)
                .addSizes (Size (10), Size (12, 6f))
                .setPosition (-50f, konfettiView.width + 50f, -50f, -50f)
                .streamFor (300, 5000L)
        }
```
You might want to remove the listener afterwards in case it gets called again.
Alternatively you can use the ktx `view.doOnNextLayout {}` if you import the android ktx core dependency

**Comment by durgesh2014** [comment]
final KonfettiView konfettiView = findViewById(R.id.viewKonfetti);
DisplayMetrics display = new DisplayMetrics();
getWindowManager().getDefaultDisplay().getMetrics(display);
konfettiView.build()
        .addColors(Color.rgb(255, 36, 0), Color.rgb(120, 116, 242), Color.rgb(255, 232, 103))
        //.addColors(Color.rgb(168,100,253), Color.rgb(255,113,141), Color.rgb(120,255,68))
        .setDirection(0.0, 359.0)
        .setSpeed(1f, 5f)
        .setFadeOutEnabled(true)
        .setTimeToLive(2000L)
        .addShapes(Shape.RECT, Shape.CIRCLE)
        .addSizes(new Size(12, 5f))
        .setPosition(-50f, display.widthPixels + 50f, -50f, -50f)
        .streamFor(300, 5000L);
