### ISSUE TITLE
Play audio while using Konfetti

### ISSUE THREAD

**Issue by ManarMustapha** [DanielMartinus/Konfetti#72]
When Play Audio in Media player and execute Konfetti ,The Audio stop.

**Comment by DanielMartinus** [comment]
Please give me more details to work with. What media plauyer is being used, is this happening in your own app or with a mediaplayer from a different app? etc. Without information there's isn't really anything that I can do for you. Thank you

**Comment by Jasperste** [comment]
Hi @ManarMustapha, is this issue still ongoing? If so, could you try to turn off the confetti code, and see if the audio still stops after 10 seconds? If that's the case you could try to remove some options and try again for each case and see if one of Confetti's options indicates something. Thanks!

**Comment by DanielMartinus** [comment]
@ManarMustapha Have you looked at this StackOverflow question? https://stackoverflow.com/questions/6241687/mediaplayer-stop-playing-after-about-5-seconds

> It was probably due to having the MediaPlayer-object only existing within a method.
