### ISSUE TITLE
Annimation Not working

### ISSUE THREAD

**Issue by MaheshwariSneha123** [DanielMartinus/Konfetti#82]
I used you library to show the animation it worked fine on moto but when i checked on S8+ it did not worked .
But I installed  your app form playstore it worked fine
What can be the issue

**Comment by MaheshwariSneha123** [comment]
it worked for me when i changed constraint layout to frame layout

**Comment by DanielMartinus** [comment]
Do you have any idea why it didn't work in the ConstraintLayout for s8? Were the constraints different for the screen size of the 8+?

Also, is this solved and can it be closed?
